FROM mysql:8.0

# Переменные окружения для инициализации базы данных
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=app_user
ENV MYSQL_PASSWORD=1234
ENV MYSQL_ROOT_PASSWORD=root_password_here

# Скрипт init.sql выполнится автоматически при первом запуске
COPY init.sql /docker-entrypoint-initdb.d/
